### ISSUE TITLE
Does not support zfs filesystem with space characters

### ISSUE THREAD

**Issue by timemaster67** [gbytedev/zfs-multi-mount#2]
This script does not support fs with space inside their name. 

How to reproduce : 
```
Create some filesystem 
# zfs list -H -o name
Tank
Tank/ParentFS
Tank/ParentFS/Sub File System
..

#./zfs-multi-mount --no-mount
ERROR: Dataset 'Tank/ParentFS/Sub' does not exist. 
```

code in error : 
```
for dataset in "${datasets[@]}"; do
  ! load_key $dataset && exit 1
```

From what I understand, the for here will split on newline, but also on space. Add an echo before load_key to easily see this. As that zfs return is not double quoted (of course) the fs with a space is returned as two element in the for. When load_key check if the partial fs exists, it exit early because the incomplete name that stop at the first space does not exists. 
I've tried to read and fix this on my own but I'm not good with bash and I'm losing too much time. Perhaps you would have a quick solution ? 
https://stackoverflow.com/questions/9084257/bash-array-with-spaces-in-elements
Thanks.

**Comment by gbytedev** [comment]
I wasn't even aware of zfs supporting space in dataset names. Seems like such a bad idea, especially in shell context. Will be taking a look as soon as I find the time!

**Comment by gbytedev** [comment]
@timemaster67 Should be working now, please test and get back to me.

**Comment by timemaster67** [comment]
It's working as expected. Thank you.
