### ISSUE TITLE
Are ZVOLs supported?

### ISSUE THREAD

**Issue by reefland** [gbytedev/zfs-multi-mount#4]
Greetings,

I'm using `ExecStart=zfs-multi-mount.sh --systemd k3s05/ROOT k3s05/rancher`

Where ` k3s05/rancher` is a ZVOL defined with:
```
k3s05/rancher  encryption            aes-256-gcm                -
k3s05/rancher  keylocation           file:///etc/zfs/zroot.key  local
k3s05/rancher  keyformat             passphrase 
```

 ` k3s05/rancher` is not getting unlocked.  At the emergency shell, I enter:
```
zfs load-key k3s05/rancher
```

Works fine.  Key becomes available and system is able to complete booting.

**Comment by c3ph3us** [comment]
@reefland what is your purpose to use the script ? 

1. ZVOL (ZFS volume) is also a ZFS dataset (but is represented as a separate block device dev/zvol/{id)/ ) - so all is the same  as datasets on pool are handled by zfs (create / load-key/unload-key etc...)  
2. using a keyfile allows encrypted ZFS volumes to be automatically mounted also at boot without any prompt for pass 
3. your import may fail from many reasons top are:
      a)  file that is described by the keylocation  property on zfs dataset is missing (not exist, the path is inaccessible as volume is not mounted yet? or same as said in point b)
      b)  inappriopriate context of  zfs load-key execution  - executing context (eg. systemd/user) has no permission to file that is described by the keylocation property   
4. keep in mind that most systemd boot flow is handled by wanted ,required,  targets - and many ops are done async 

why wrapping another layer (service in service in service) around task you could handle by  one simple systemd unit  - the reason for use such script is to gather input which normally  not done via other zfs generic systemd unit files  like zfs-mount.service 

all knowledge for you on zfs autostart in pill:

https://wiki.archlinux.org/title/ZFS#Automatic_Start

**Comment by reefland** [comment]
Sorry, this was resolved months ago.  Don't recall root cause.  closing.
